In [2]:
import pandas as pd
import numpy as np
import requests
pd.set_option('display.max_columns', None)
import time

In [28]:
test_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season=2012-13&SeasonType=Regular%20Season&StatCategory=PTS'

In [29]:
r = requests.get(url=test_url).json()

In [30]:
table_headers = r['resultSet']['headers']

In [31]:
pd.DataFrame(r['resultSet']['rowSet'], columns = table_headers)

,PLAYER_ID,RANK,PLAYER,TEAM_ID,TEAM,GP,MIN,FGM,FGA,FG_PCT,FG3M,FG3A,FG3_PCT,FTM,FTA,FT_PCT,OREB,DREB,REB,AST,STL,BLK,TOV,PF,PTS,EFF,AST_TOV,STL_TOV
0,201142,1,Kevin Durant,1610612760,OKC,81,3119,731,1433,0.510,139,334,0.416,679,750,0.905,46,594,640,374,116,105,280,143,2280,2462,1.34,0.41
1,977,2,Kobe Bryant,1610612747,LAL,78,3013,738,1595,0.463,132,407,0.324,525,626,0.839,66,367,433,469,106,25,287,173,2133,1921,1.63,0.37
2,2544,3,LeBron James,1610612748,MIA,76,2877,765,1354,0.565,103,254,0.406,403,535,0.753,97,513,610,551,129,67,226,110,2036,2446,2.44,0.57
3,201935,4,James Harden,1610612745,HOU,78,2985,585,1337,0.438,179,486,0.368,674,792,0.851,62,317,379,455,142,38,295,178,2023,1872,1.54,0.48
4,2546,5,Carmelo Anthony,1610612752,NYK,67,2482,669,1489,0.449,157,414,0.379,425,512,0.830,134,326,460,171,52,32,175,205,1920,1553,0.98,0.30
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
463,203130,463,Darius Johnson-Odom,1610612747,LAL,4,6,0,4,0.000,0,1,0.000,0,0,0.000,1,3,4,1,0,0,0,0,0,1,0.00,0.00
464,2545,463,Darko Milicic,1610612738,BOS,1,5,0,1,0.000,0,0,0.000,0,0,0.000,0,1,1,0,0,0,2,1,0,-2,0.00,0.00
465,202458,463,Justin Dentmon,1610612742,DAL,2,4,0,2,0.000,0,0,0.000,0,0,0.000,0,0,0,0,0,0,0,0,0,-2,0.00,0.00
466,2679,463,Matt Carroll,1610612766,CHA,1,6,0,0,0.000,0,0,0.000,0,0,0.000,0,0,0,1,0,0,0,1,0,1,0.00,0.00
467,200780,463,Solomon Jones,1610612752,NYK,2,26,0,1,0.000,0,0,0.000,0,0,0.000,1,2,3,0,0,1,3,3,0,0,0.00,0.00

In [38]:
del temp_df1, temp_df2, temp_df3

In [39]:
df_cols = ['YEAR', 'SEASON_TYPE'] + table_headers

In [40]:
pd.DataFrame(columns = df_cols)

Empty DataFrame
Columns: [YEAR, SEASON_TYPE, PLAYER_ID, RANK, PLAYER, TEAM_ID, TEAM, GP, MIN, FGM, FGA, FG_PCT, FG3M, FG3A, FG3_PCT, FTM, FTA, FT_PCT, OREB, DREB, REB, AST, STL, BLK, TOV, PF, PTS, EFF, AST_TOV, STL_TOV]
Index: []

In [41]:
headers = {
    'Accept': '*/*',
    'Accept-Encoding': 'gzip, deflate, br, zstd',
    'Accept-Language': 'pt-BR,pt;q=0.8',
    'Connection': 'keep-alive',
    'Host': 'stats.nba.com',
    'Origin': 'https://www.nba.com',
    'Referer': 'https://www.nba.com/',
    'Sec-Ch-Ua': '"Brave";v="123", "Not:A-Brand";v="8", "Chromium";v="123"',
    'Sec-Ch-Ua-Mobile': '?0',
    'Sec-Ch-Ua-Platform': '"Windows"',
    'Sec-Fetch-Dest': 'empty',
    'Sec-Fetch-Mode': 'cors',
    'Sec-Fetch-Site': 'same-site',
    'Sec-Gpc': '1',
    'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36'
}

In [48]:
df = pd.DataFrame(columns = df_cols)
season_types = ['Regular%20Season', 'Playoffs']
years = ['2012-13', '2013-14', '2014-15', '2015-16', '2016-17', '2017-18', '2018-19', '2019-20', '2021-22', '2022-23']

begin_loop = time.time()

for y in years:
    for s in season_types:
        api_url = 'https://stats.nba.com/stats/leagueLeaders?LeagueID=00&PerMode=Totals&Scope=S&Season='+y+'&SeasonType='+s+'&StatCategory=PTS'
        r = requests.get(url=api_url).json()
        temp_df1 = pd.DataFrame(r['resultSet']['rowSet'], columns=table_headers)
        temp_df2 = pd.DataFrame({'YEAR':[y for i in range(len(temp_df1))],
                                 'SEASON_TYPE':[s for i in range(len(temp_df1))]})
        temp_df3 = pd.concat([temp_df2,temp_df1], axis=1)
        df = pd.concat([df, temp_df3], axis=0)
        print(f'Finish scraping data from {y} {s}.')
        lag = np.random.uniform(low=5, high=30)
        print(f'Waiting {round(lag,1)} seconds.')
        time.sleep(lag)
        
print(f'Process complete! Total run time: {round((time.time() - begin_loop)/60,2)}')
df.to_excel('nba_players_data.xlsx', index=False)

Finish scraping data from 2012-13 Regular%20Season.
Waiting 26.8 seconds.
Finish scraping data from 2012-13 Playoffs.
Waiting 8.2 seconds.
Finish scraping data from 2013-14 Regular%20Season.
Waiting 14.1 seconds.
Finish scraping data from 2013-14 Playoffs.
Waiting 22.1 seconds.
Finish scraping data from 2014-15 Regular%20Season.
Waiting 23.6 seconds.
Finish scraping data from 2014-15 Playoffs.
Waiting 16.6 seconds.
Finish scraping data from 2015-16 Regular%20Season.
Waiting 6.4 seconds.
Finish scraping data from 2015-16 Playoffs.
Waiting 23.2 seconds.
Finish scraping data from 2016-17 Regular%20Season.
Waiting 6.6 seconds.
Finish scraping data from 2016-17 Playoffs.
Waiting 27.7 seconds.
Finish scraping data from 2017-18 Regular%20Season.
Waiting 10.0 seconds.
Finish scraping data from 2017-18 Playoffs.
Waiting 24.6 seconds.
Finish scraping data from 2018-19 Regular%20Season.
Waiting 22.3 seconds.
Finish scraping data from 2018-19 Playoffs.
Waiting 7.4 seconds.
Finish scraping data from 2019-20 Regular%20Season.
Waiting 23.4 seconds.
Finish scraping data from 2019-20 Playoffs.
Waiting 13.4 seconds.
Finish scraping data from 2021-22 Regular%20Season.
Waiting 7.4 seconds.
Finish scraping data from 2021-22 Playoffs.
Waiting 22.3 seconds.
Finish scraping data from 2022-23 Regular%20Season.
Waiting 10.2 seconds.
Finish scraping data from 2022-23 Playoffs.
Waiting 30.0 seconds.
Process complete! Total run time: 6.0